export const REPORT_LIST_REQUEST = 'REPORT_LIST_REQUEST'
export const REPORT_LIST_SUCCESS = 'REPORT_LIST_SUCCESS'
export const REPORT_LIST_FAIL = 'REPORT_LIST_FAIL'

export const SUMMARY_REQUEST = 'SUMMARY_REQUEST'
export const SUMMARY_SUCCESS = 'SUMMARY_SUCCESS'
export const SUMMARY_FAIL = 'SUMMARY_FAIL'